# Pure White Console Color Matrix
background=#ffffff
foreground=#000000
cursor=#000000

# Standard ANSI Palette Structure (Darker Accents for Light Mode)
color0=#000000
color1=#a61717
color2=#127320
color3=#a36800
color4=#00439c
color5=#6c1da8
color6=#007080
color7=#707070

# Bright / Intense Variables
color8=#555555
color9=#e01b1b
color10=#1cb834
color11=#e09000
color12=#0062e3
color13=#9b2ee0
color14=#00a1b8
color15=#ffffff
